### ISSUE TITLE
Errors when running ./scripts/quick_run.sh

### ISSUE THREAD

**Issue by eddyhkchiu** [UT-Austin-RPL/Coopernaut#4]
Hi,

I was trying to run ./scripts/quick_run.sh but I got several error messages.
After the code finishes running, the result folder only contains subfolders like result/SCENARIO_ID/BirdeyeViewDebug/ without actual output files inside. I wonder what could be the problem?
Thanks!

The followings are the error messages:
Mqtt port 4909
[20.   6.  40.  57.5  0. ]
Traffic Port 3149
Mqtt port 4910
[20.  6. 40. 60.  0.]
sh: 1: fuser: not found
sh: 1: fuser: not found
sh: 1: fuser: not found
...
sh: 1: fuser: not found
sh: 1: fuser: not found
sh: 1: fuser: not found
0 27
1 27
(pid=27522) pygame 2.1.2 (SDL 2.0.16, Python 3.7.12)
(pid=27522) Hello from the pygame community. https://www.pygame.org/contribute.html
(pid=27548) pygame 2.1.2 (SDL 2.0.16, Python 3.7.12)
(pid=27548) Hello from the pygame community. https://www.pygame.org/contribute.html
(pid=27522) /opt/conda/envs/autocast/lib/python3.7/site-packages/MinkowskiEngine-0.5.4-py3.7-linux-x86_64.egg/MinkowskiEngine/__init__.py:225: UserWarning: The MinkowskiEngine was compiled with CPU_ONLY flag. If you want to compile with CUDA support, make sure `torch.cuda.is_available()` is True when you install MinkowskiEngine.
(pid=27522)   "If you want to compile with CUDA support, make sure `torch.cuda.is_available()` is True when you install MinkowskiEngine.",
(WorkerScenarioRunner pid=27522) Collider is NOT sharing
(WorkerScenarioRunner pid=27522) TraceID 0, Ego spd 20.0,dist 6.0, collider spd 30.0, dist 40.0, accel 0.0
(WorkerScenarioRunner pid=27522) &&&&&&&&&&&&&&&&&&&&Initialization
(WorkerScenarioRunner pid=27522) Util.mqtt_port: 4884
(WorkerScenarioRunner pid=27522) Traffic manager port 3123
(pid=27548) /opt/conda/envs/autocast/lib/python3.7/site-packages/MinkowskiEngine-0.5.4-py3.7-linux-x86_64.egg/MinkowskiEngine/__init__.py:225: UserWarning: The MinkowskiEngine was compiled with CPU_ONLY flag. If you want to compile with CUDA support, make sure `torch.cuda.is_available()` is True when you install MinkowskiEngine.
(pid=27548)   "If you want to compile with CUDA support, make sure `torch.cuda.is_available()` is True when you install MinkowskiEngine.",
(WorkerScenarioRunner pid=27548) Collider is NOT sharing
(WorkerScenarioRunner pid=27548) TraceID 1, Ego spd 20.0,dist 6.0, collider spd 30.0, dist 42.5, accel 0.0
(WorkerScenarioRunner pid=27548) &&&&&&&&&&&&&&&&&&&&Initialization
(WorkerScenarioRunner pid=27548) Util.mqtt_port: 4885
(WorkerScenarioRunner pid=27548) Traffic manager port 3124
(WorkerScenarioRunner pid=27522) 
(WorkerScenarioRunner pid=27522) --------------------------------------------------------------------------------
(WorkerScenarioRunner pid=27522) 
(WorkerScenarioRunner pid=27522)  Using the Open3D PyTorch ops with CUDA 11 may have stability issues!
(WorkerScenarioRunner pid=27522) 
(WorkerScenarioRunner pid=27522)  We recommend to compile PyTorch from source with compile flags
(WorkerScenarioRunner pid=27522)    '-Xcompiler -fno-gnu-unique'
(WorkerScenarioRunner pid=27522) 
(WorkerScenarioRunner pid=27522)  or use the PyTorch wheels at
(WorkerScenarioRunner pid=27522)    https://github.com/intel-isl/open3d_downloads/releases/tag/torch1.7.1
(WorkerScenarioRunner pid=27522) 
(WorkerScenarioRunner pid=27522) 
(WorkerScenarioRunner pid=27522)  Ignore this message if PyTorch has been compiled with the aforementioned
(WorkerScenarioRunner pid=27522)  flags.
(WorkerScenarioRunner pid=27522) 
(WorkerScenarioRunner pid=27522)  See https://github.com/intel-isl/Open3D/issues/3324 and
(WorkerScenarioRunner pid=27522)  https://github.com/pytorch/pytorch/issues/52663 for more information on this
(WorkerScenarioRunner pid=27522)  problem.
(WorkerScenarioRunner pid=27522) 
(WorkerScenarioRunner pid=27522) --------------------------------------------------------------------------------
(WorkerScenarioRunner pid=27522) 
(WorkerScenarioRunner pid=27548) 
(WorkerScenarioRunner pid=27548) --------------------------------------------------------------------------------
(WorkerScenarioRunner pid=27548) 
(WorkerScenarioRunner pid=27548)  Using the Open3D PyTorch ops with CUDA 11 may have stability issues!
(WorkerScenarioRunner pid=27548) 
(WorkerScenarioRunner pid=27548)  We recommend to compile PyTorch from source with compile flags
(WorkerScenarioRunner pid=27548)    '-Xcompiler -fno-gnu-unique'
(WorkerScenarioRunner pid=27548) 
(WorkerScenarioRunner pid=27548)  or use the PyTorch wheels at
(WorkerScenarioRunner pid=27548)    https://github.com/intel-isl/open3d_downloads/releases/tag/torch1.7.1
(WorkerScenarioRunner pid=27548) 
(WorkerScenarioRunner pid=27548) 
(WorkerScenarioRunner pid=27548)  Ignore this message if PyTorch has been compiled with the aforementioned
(WorkerScenarioRunner pid=27548)  flags.
(WorkerScenarioRunner pid=27548) 
(WorkerScenarioRunner pid=27548)  See https://github.com/intel-isl/Open3D/issues/3324 and
(WorkerScenarioRunner pid=27548)  https://github.com/pytorch/pytorch/issues/52663 for more information on this
(WorkerScenarioRunner pid=27548)  problem.
(WorkerScenarioRunner pid=27548) 
(WorkerScenarioRunner pid=27548) --------------------------------------------------------------------------------
(WorkerScenarioRunner pid=27548) 
(WorkerScenarioRunner pid=27522) ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
(WorkerScenarioRunner pid=27522) ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
(WorkerScenarioRunner pid=27522) ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
(WorkerScenarioRunner pid=27522) ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
(WorkerScenarioRunner pid=27522) ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
(WorkerScenarioRunner pid=27522) ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
(WorkerScenarioRunner pid=27522) ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
(WorkerScenarioRunner pid=27522) ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM default
(WorkerScenarioRunner pid=27522) Finished initializing scenario manager
(WorkerScenarioRunner pid=27548) ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
(WorkerScenarioRunner pid=27548) ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
(WorkerScenarioRunner pid=27548) ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
(WorkerScenarioRunner pid=27548) ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
(WorkerScenarioRunner pid=27548) ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
(WorkerScenarioRunner pid=27548) ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
(WorkerScenarioRunner pid=27548) ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
(WorkerScenarioRunner pid=27548) ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM default
(WorkerScenarioRunner pid=27522) Util.mqtt_port: 4884
(WorkerScenarioRunner pid=27522) Binding Mqtt... 4884
(WorkerScenarioRunner pid=27522) Background Traffic 30
(WorkerScenarioRunner pid=27522) ['AutoCastSim/srunner/data/routes_training_town01_autocast6.xml', 'AutoCastSim/srunner/data/towns01_traffic_scenarios_autocast6.json']
(WorkerScenarioRunner pid=27522) sh: 1: mosquitto: not found
(WorkerScenarioRunner pid=27548) Finished initializing scenario manager
(WorkerScenarioRunner pid=27548) Util.mqtt_port: 4885
(WorkerScenarioRunner pid=27548) Binding Mqtt... 4885
(WorkerScenarioRunner pid=27548) Background Traffic 30
(WorkerScenarioRunner pid=27548) ['AutoCastSim/srunner/data/routes_training_town01_autocast6.xml', 'AutoCastSim/srunner/data/towns01_traffic_scenarios_autocast6.json']
(WorkerScenarioRunner pid=27548) sh: 1: mosquitto: not found
(WorkerScenarioRunner pid=27522) process control seed: 8512
(WorkerScenarioRunner pid=27522) Setting traffic manager seed: 4291
(WorkerScenarioRunner pid=27522) Finished HUD world setting
(WorkerScenarioRunner pid=27522) Loading Point Transformer models
(WorkerScenarioRunner pid=27522) Loading Checkpoint model-105.th
(WorkerScenarioRunner pid=27522) Using Device: cuda
(WorkerScenarioRunner pid=27522) Using Cooperative Point Transformer
(WorkerScenarioRunner pid=27548) process control seed: 8779
(WorkerScenarioRunner pid=27548) Setting traffic manager seed: 531
(WorkerScenarioRunner pid=27548) Finished HUD world setting
(WorkerScenarioRunner pid=27548) Loading Point Transformer models
(WorkerScenarioRunner pid=27548) Loading Checkpoint model-105.th
(WorkerScenarioRunner pid=27548) Using Device: cuda
(WorkerScenarioRunner pid=27548) Using Cooperative Point Transformer
(WorkerScenarioRunner pid=27522) Loading model and initializing  ckpts/model-105.th
(WorkerScenarioRunner pid=27522) Preparing scenario: RouteScenario_0
(WorkerScenarioRunner pid=27522) scenario MasterScenario added
(WorkerScenarioRunner pid=27522) Creating scenario 6 behavior
(WorkerScenarioRunner pid=27522) Finished scenario 6 behavior
(WorkerScenarioRunner pid=27522) scenario ManeuverOppositeDirection added
(WorkerScenarioRunner pid=27522) scenario Parallel added
(WorkerScenarioRunner pid=27522) registering sensor 259_RGB
(WorkerScenarioRunner pid=27522) finished registering sensor 259_RGB
(WorkerScenarioRunner pid=27522) registering sensor 259_LIDAR
(WorkerScenarioRunner pid=27522) finished registering sensor 259_LIDAR
(WorkerScenarioRunner pid=27522) [Errno 111] Connection refused
(WorkerScenarioRunner pid=27522) Traceback (most recent call last):
(WorkerScenarioRunner pid=27522)   File "/home/eddy/Research/Coopernaut/AutoCastSim/scenario_runner.py", line 464, in _load_and_run_scenario
(WorkerScenarioRunner pid=27522)     self.manager.load_scenario(scenario, self.agent_instance)
(WorkerScenarioRunner pid=27522)   File "/home/eddy/Research/Coopernaut/AutoCastSim/srunner/scenariomanager/scenario_manager.py", line 216, in load_scenario
(WorkerScenarioRunner pid=27522)     self._agent.setup_collaborator(self.ego_vehicles[0], self.sharing_session)
(WorkerScenarioRunner pid=27522)   File "/home/eddy/Research/Coopernaut/AutoCastSim/srunner/autoagents/agent_wrapper.py", line 150, in setup_collaborator
(WorkerScenarioRunner pid=27522)     self._collaborator_dict[vehicle.id] = Collaborator(vehicle, self._agent, self, sharing)
(WorkerScenarioRunner pid=27522)   File "/home/eddy/Research/Coopernaut/AutoCastSim/AVR/Collaborator.py", line 86, in __init__
(WorkerScenarioRunner pid=27522)     self.ControlChannel = Comm.Comm(self, Comm.beacon_topic)
(WorkerScenarioRunner pid=27522)   File "/home/eddy/Research/Coopernaut/AutoCastSim/AVR/Comm.py", line 160, in __init__
(WorkerScenarioRunner pid=27522)     self.client.connect(broker, port=Utils.mqtt_port)
(WorkerScenarioRunner pid=27522)   File "/opt/conda/envs/autocast/lib/python3.7/site-packages/paho/mqtt/client.py", line 914, in connect
(WorkerScenarioRunner pid=27522)     return self.reconnect()
(WorkerScenarioRunner pid=27522)   File "/opt/conda/envs/autocast/lib/python3.7/site-packages/paho/mqtt/client.py", line 1044, in reconnect
(WorkerScenarioRunner pid=27522)     sock = self._create_socket_connection()
(WorkerScenarioRunner pid=27522)   File "/opt/conda/envs/autocast/lib/python3.7/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
(WorkerScenarioRunner pid=27522)     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
(WorkerScenarioRunner pid=27522)   File "/opt/conda/envs/autocast/lib/python3.7/socket.py", line 728, in create_connection
(WorkerScenarioRunner pid=27522)     raise err
(WorkerScenarioRunner pid=27522)   File "/opt/conda/envs/autocast/lib/python3.7/socket.py", line 716, in create_connection
(WorkerScenarioRunner pid=27522)     sock.connect(sa)
(WorkerScenarioRunner pid=27522) ConnectionRefusedError: [Errno 111] Connection refused
(WorkerScenarioRunner pid=27522) Compiling Video for ./result//0/BirdeyeViewDebug///0_hud_info_*.jpg
(WorkerScenarioRunner pid=27522) Compiling Video for ./result//0/BirdeyeViewDebug///1_PC_*.jpg
(WorkerScenarioRunner pid=27522) Compiling Video for ./result//0/BirdeyeViewDebug///2_RGB_*.jpg
(WorkerScenarioRunner pid=27522) No more scenarios .... Exiting
(WorkerScenarioRunner pid=27548) Loading model and initializing  ckpts/model-105.th
(WorkerScenarioRunner pid=27548) Preparing scenario: RouteScenario_0
(WorkerScenarioRunner pid=27548) scenario MasterScenario added
(WorkerScenarioRunner pid=27548) Creating scenario 6 behavior
(WorkerScenarioRunner pid=27548) Finished scenario 6 behavior
(WorkerScenarioRunner pid=27548) scenario ManeuverOppositeDirection added
(WorkerScenarioRunner pid=27548) scenario Parallel added
(WorkerScenarioRunner pid=27548) registering sensor 259_RGB
(WorkerScenarioRunner pid=27548) finished registering sensor 259_RGB
(WorkerScenarioRunner pid=27548) registering sensor 259_LIDAR
(WorkerScenarioRunner pid=27548) finished registering sensor 259_LIDAR
(WorkerScenarioRunner pid=27548) [Errno 111] Connection refused
(WorkerScenarioRunner pid=27548) Traceback (most recent call last):
(WorkerScenarioRunner pid=27548)   File "/home/eddy/Research/Coopernaut/AutoCastSim/scenario_runner.py", line 464, in _load_and_run_scenario
(WorkerScenarioRunner pid=27548)     self.manager.load_scenario(scenario, self.agent_instance)
(WorkerScenarioRunner pid=27548)   File "/home/eddy/Research/Coopernaut/AutoCastSim/srunner/scenariomanager/scenario_manager.py", line 216, in load_scenario
(WorkerScenarioRunner pid=27548)     self._agent.setup_collaborator(self.ego_vehicles[0], self.sharing_session)
(WorkerScenarioRunner pid=27548)   File "/home/eddy/Research/Coopernaut/AutoCastSim/srunner/autoagents/agent_wrapper.py", line 150, in setup_collaborator
(WorkerScenarioRunner pid=27548)     self._collaborator_dict[vehicle.id] = Collaborator(vehicle, self._agent, self, sharing)
(WorkerScenarioRunner pid=27548)   File "/home/eddy/Research/Coopernaut/AutoCastSim/AVR/Collaborator.py", line 86, in __init__
(WorkerScenarioRunner pid=27548)     self.ControlChannel = Comm.Comm(self, Comm.beacon_topic)
(WorkerScenarioRunner pid=27548)   File "/home/eddy/Research/Coopernaut/AutoCastSim/AVR/Comm.py", line 160, in __init__
(WorkerScenarioRunner pid=27548)     self.client.connect(broker, port=Utils.mqtt_port)
(WorkerScenarioRunner pid=27548)   File "/opt/conda/envs/autocast/lib/python3.7/site-packages/paho/mqtt/client.py", line 914, in connect
(WorkerScenarioRunner pid=27548)     return self.reconnect()
(WorkerScenarioRunner pid=27548)   File "/opt/conda/envs/autocast/lib/python3.7/site-packages/paho/mqtt/client.py", line 1044, in reconnect
(WorkerScenarioRunner pid=27548)     sock = self._create_socket_connection()
(WorkerScenarioRunner pid=27548)   File "/opt/conda/envs/autocast/lib/python3.7/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
(WorkerScenarioRunner pid=27548)     return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
(WorkerScenarioRunner pid=27548)   File "/opt/conda/envs/autocast/lib/python3.7/socket.py", line 728, in create_connection
(WorkerScenarioRunner pid=27548)     raise err
(WorkerScenarioRunner pid=27548)   File "/opt/conda/envs/autocast/lib/python3.7/socket.py", line 716, in create_connection
(WorkerScenarioRunner pid=27548)     sock.connect(sa)
(WorkerScenarioRunner pid=27548) ConnectionRefusedError: [Errno 111] Connection refused
(WorkerScenarioRunner pid=27548) Compiling Video for ./result//1/BirdeyeViewDebug///0_hud_info_*.jpg
(WorkerScenarioRunner pid=27548) Compiling Video for ./result//1/BirdeyeViewDebug///1_PC_*.jpg
(WorkerScenarioRunner pid=27548) Compiling Video for ./result//1/BirdeyeViewDebug///2_RGB_*.jpg
(WorkerScenarioRunner pid=27548) No more scenarios .... Exiting
sh: 1: fuser: not found
sh: 1: fuser: not found
sh: 1: fuser: not found
sh: 1: fuser: not found
...
sh: 1: fuser: not found
sh: 1: fuser: not found
sh: 1: fuser: not found
sh: 1: fuser: not found
Scenario Done! 2
2 27
(pid=27774) pygame 2.1.2 (SDL 2.0.16, Python 3.7.12)
(pid=27774) Hello from the pygame community. https://www.pygame.org/contribute.html
3 27
(pid=27774) /opt/conda/envs/autocast/lib/python3.7/site-packages/MinkowskiEngine-0.5.4-py3.7-linux-x86_64.egg/MinkowskiEngine/__init__.py:225: UserWarning: The MinkowskiEngine was compiled with CPU_ONLY flag. If you want to compile with CUDA support, make sure `torch.cuda.is_available()` is True when you install MinkowskiEngine.
(pid=27774)   "If you want to compile with CUDA support, make sure `torch.cuda.is_available()` is True when you install MinkowskiEngine.",
(pid=27814) pygame 2.1.2 (SDL 2.0.16, Python 3.7.12)
(pid=27814) Hello from the pygame community. https://www.pygame.org/contribute.html
(WorkerScenarioRunner pid=27774) Collider is NOT sharing
(WorkerScenarioRunner pid=27774) TraceID 2, Ego spd 20.0,dist 6.0, collider spd 30.0, dist 45.0, accel 0.0
(WorkerScenarioRunner pid=27774) &&&&&&&&&&&&&&&&&&&&Initialization
(WorkerScenarioRunner pid=27774) Util.mqtt_port: 4886
(WorkerScenarioRunner pid=27774) Traffic manager port 3125
(WorkerScenarioRunner pid=27774) 
(WorkerScenarioRunner pid=27774) --------------------------------------------------------------------------------
(WorkerScenarioRunner pid=27774) 
(WorkerScenarioRunner pid=27774)  Using the Open3D PyTorch ops with CUDA 11 may have stability issues!
(WorkerScenarioRunner pid=27774) 
(WorkerScenarioRunner pid=27774)  We recommend to compile PyTorch from source with compile flags
(WorkerScenarioRunner pid=27774)    '-Xcompiler -fno-gnu-unique'
(WorkerScenarioRunner pid=27774) 
(WorkerScenarioRunner pid=27774)  or use the PyTorch wheels at
(WorkerScenarioRunner pid=27774)    https://github.com/intel-isl/open3d_downloads/releases/tag/torch1.7.1
(WorkerScenarioRunner pid=27774) 
(WorkerScenarioRunner pid=27774) 
(WorkerScenarioRunner pid=27774)  Ignore this message if PyTorch has been compiled with the aforementioned
(WorkerScenarioRunner pid=27774)  flags.
(WorkerScenarioRunner pid=27774) 
(WorkerScenarioRunner pid=27774)  See https://github.com/intel-isl/Open3D/issues/3324 and
(WorkerScenarioRunner pid=27774)  https://github.com/pytorch/pytorch/issues/52663 for more information on this
(WorkerScenarioRunner pid=27774)  problem.
(WorkerScenarioRunner pid=27774) 
(WorkerScenarioRunner pid=27774) --------------------------------------------------------------------------------
(WorkerScenarioRunner pid=27774) 
(WorkerScenarioRunner pid=27774) ALSA lib confmisc.c:767:(parse_card) cannot find card '0'

// repeat for each scenario

**Comment by cuijiaxun** [comment]
try
`sudo apt-get install mosquitto libopenblas-dev`

**Comment by eddyhkchiu** [comment]
Thank you!
