### ISSUE TITLE
MinkowskiEngine Git Error: <File not found>

### ISSUE THREAD

**Issue by obadul024** [UT-Austin-RPL/Coopernaut#5]
I used the detailed installation manual and when I reached the step;

`pip install -U git+https://github.com/NVIDIA/MinkowskiEngine@f81ae66b33b883cd08ee4f64d08cf633608b118 -v --no-deps --install-option="--blas_include_dirs=${CONDA_PREFIX}/include"  --install-option="--blas=openblas"
`

I got the error; 

`Collecting git+https://github.com/NVIDIA/MinkowskiEngine@f81ae66b33b883cd08ee4f64d08cf633608b118
  Cloning https://github.com/NVIDIA/MinkowskiEngine (to revision f81ae66b33b883cd08ee4f64d08cf633608b118) to /tmp/pip-req-build-ei4fvef0
  Running command git version
  git version 2.25.1
  Running command git clone --filter=blob:none -q https://github.com/NVIDIA/MinkowskiEngine /tmp/pip-req-build-ei4fvef0
  Running command git show-ref f81ae66b33b883cd08ee4f64d08cf633608b118
  WARNING: Did not find branch or tag 'f81ae66b33b883cd08ee4f64d08cf633608b118', assuming revision or ref.
  Running command git rev-parse HEAD
  405b39cb7e68c2ec1b4ac8c4b4ca9fa6fcfcb2fc
  Running command git checkout -q f81ae66b33b883cd08ee4f64d08cf633608b118
  error: pathspec 'f81ae66b33b883cd08ee4f64d08cf633608b118' did not match any file(s) known to git
WARNING: Discarding git+https://github.com/NVIDIA/MinkowskiEngine@f81ae66b33b883cd08ee4f64d08cf633608b118. Command errored out with exit status 1: git checkout -q f81ae66b33b883cd08ee4f64d08cf633608b118 Check the logs for full command output.
ERROR: Command errored out with exit status 1: git checkout -q f81ae66b33b883cd08ee4f64d08cf633608b118 Check the logs for full command output.
`
I checked the link and the commit does not seem to exist anymore
Please any help would be appreciated

**Comment by cuijiaxun** [comment]
Try installing CPU version MinkowskiEngine from source?
Install CPU Minkowski
DIR=$(pwd);
cd ..;
git clone https://github.com/NVIDIA/MinkowskiEngine.git;
cd MinkowskiEngine;
python setup.py install --cpu_only;
cd ${DIR};

**Comment by obadul024** [comment]
thanks for replying, I did that eventually

**Comment by ShawnKing98** [comment]
> Try installing CPU version MinkowskiEngine from source? Install CPU Minkowski DIR=$(pwd); cd ..; git clone https://github.com/NVIDIA/MinkowskiEngine.git; cd MinkowskiEngine; python setup.py install --cpu_only; cd ${DIR};

Thanks, this works for me
