### ISSUE TITLE
cd MinkowskiEngine; python setup.py install --cpu_only;

### ISSUE THREAD

**Issue by 1146065545** [UT-Austin-RPL/Coopernaut#9]
why use cpu ?
why not use gpu????????????????

**Comment by 1146065545** [comment]
why??
this is written in install.sh?
i dont understand

**Comment by cuijiaxun** [comment]
This issue has been resolved through private communication.
Reason for installing cpu version of MinkowskiEngine: compatibility with PyTorch and we only used the farthest pooling which does not require GPU acceleration.
